AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager secrets for RDS SQL Server and Redshift

Parameters:
  Environment:
    Type: String
    Default: dev
  Prefix:
    Type: String
    Default: gp

Resources:

  SqlServerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "connection_parameters_sqlserver-${Environment}"
      Description: "SQL Server connection credentials"
      SecretString: !Sub |
        {
          "username": "sqladmin",
          "password": "SqlPaSS2025",
          "engine": "sqlserver",
          "host": "sqlserverrds.${Environment}.rds.amazonaws.com",
          "port": 1433,
          "dbname": "globalpartners"
        }
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-sqlserver-secret-${Environment}"

  RedshiftSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "connection_parameters_redshift-${Environment}"
      Description: "Redshift connection credentials"
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "RedPaSS2025",
          "jdbc_url": "jdbc:redshift://gp-redshift-wg-${Environment}.${AWS::Region}.redshift-serverless.amazonaws.com:5439/dev"
        }
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-redshift-secret-${Environment}"
        - Key: RedshiftUser
          Value: admin


Outputs:
  SqlServerSecretArn:
    Value: !Ref SqlServerSecret
    Export:
      Name: !Sub "${AWS::StackName}-SqlServerSecretArn"

  RedshiftSecretArn:
    Description: ARN of Redshift secret
    Value: !Ref RedshiftSecret
    Export:
      Name: RedshiftSecretArn
