AWSTemplateFormatVersion: '2010-09-09'
Description: RDS SQL Server instance

Parameters:
  Prefix:
    Type: String
    Default: gp
  Environment:
    Type: String
    Default: dev

  DBInstanceClass:
    Type: String
    # Pick a class valid for SQL Server in your region
    Default: db.m5.large
    AllowedPattern: '^db\.[a-z0-9]+\.[a-z0-9]+$'
    Description: RDS instance class (e.g., db.m5.large)

  DBAllocatedStorage:
    Type: Number
    Default: 100
    MinValue: 20
    Description: Allocated storage (GiB)

  # Optional: make the secrets export name configurable to avoid hardcoding the stack name
  SecretExportName:
    Type: String
    Default: secrets-stack-SqlServerSecretArn
    Description: CloudFormation export name that contains the Secrets Manager ARN

Resources:
  SqlServerInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${Prefix}-sqlserver-${Environment}"
      Engine: sqlserver-ex                # or sqlserver-se / sqlserver-enterprise / sqlserver-web
      # Tip: consider making EngineVersion a parameter or omit to let AWS choose a supported default
      EngineVersion: 15.00.4430.1.v1
      LicenseModel: license-included
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2                    # consider 'gp3' if available in your region

      # Dynamic references to the secret (import the ARN from another stack)
      MasterUsername:
        Fn::Sub:
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:username}}"
          - { SecretArn: { "Fn::ImportValue": { "Ref": "SecretExportName" } } }
      MasterUserPassword:
        Fn::Sub:
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:password}}"
          - { SecretArn: { "Fn::ImportValue": { "Ref": "SecretExportName" } } }

      DBSubnetGroupName: !ImportValue network-stack-PublicDBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue network-stack-SQLServerSG
      PubliclyAccessible: true
      BackupRetentionPeriod: 7
      MultiAZ: false
      DeletionProtection: false
      CopyTagsToSnapshot: true

Outputs:
  SqlServerEndpoint:
    Description: SQL Server endpoint
    Value: !GetAtt SqlServerInstance.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-SqlServerEndpoint"
