AWSTemplateFormatVersion: 2010-09-09
Description: Glue jobs for ingesting, transforming, and applying data quality checks from SQL Server to Redshift

Parameters:
  Prefix:
    Type: String
    Default: gp
  Environment:
    Type: String
    Default: dev
  S3Bucket:
    Type: String
    Default: gp-elt-657082399901-dev  #'s3://gp-elt-657082399901-dev/scripts/ingest-elt.py'
  SqlServerSecretArn:
    Type: String
    Default: arn:aws:secretsmanager:us-east-1:657082399901:secret:connection_parameters_sqlserver-dev
  GlueJobRoleArn:
    Type: String
    Default: arn:aws:iam::657082399901:role/gp-glue-job-role-dev

Resources:

  IncrementJob:
    Type: AWS::Glue::Job
    Properties:  
      Name: !Sub "${Prefix}-increment-ingest-${Environment}"
      Role: !Ref GlueJobRoleArn
      GlueVersion: 4.0
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Sub 's3://${S3Bucket}/scripts/go-iincrement-ingest-elt.py'
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": "true"
        "--TempDir": !Sub 's3://${S3Bucket}/temp/'
        "--LOAD_PATH": !Sub 's3://${S3Bucket}/landing/'
        "--ERROR_PATH": !Sub 's3://${S3Bucket}/error/increment-ingest/'
        "--TABLES_INGEST": "dbo.order_item_options,dbo.order_items,dbo.date_dim"
        "CONNECTION_NAME": "custom-sqlserver-connection"
        "BOOKMARK_PATH": "s3://${S3Bucket}/items/bookmarks/"
        "WATERMARK_COLUMN": "updated_at"
        "LOAD_MODE": "incremental"  # or "full"
        "PRIMARY_KEYS": "dbo.order_item_options:order_id,lineitem_id|dbo.order_items:order_id,lineitem_id"
        "--SECRET_ID": !Ref SqlServerSecretArn,
        "--extra-jars": !Sub "s3://${S3Bucket}/drivers/sqljdbc42.jar"
        "--job-bookmark-option": "job-bookmark-enable"

  TransformJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${Prefix}-transform-${Environment}"
      Role: !Ref GlueJobRoleArn
      GlueVersion: 4.0
      NumberOfWorkers: 10
      WorkerType: G.1X
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Sub 's3://${S3Bucket}/scripts/go-transform-elt.py'
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": "true"
        "--TempDir": !Sub 's3://${S3Bucket}/temp/'
        "--LOAD_PATH": !Sub 's3://${S3Bucket}/landing/'
        "--TRANSFORM_PATH": !Sub 's3://${S3Bucket}/transform/'
        "--PROCESS_PATH": !Sub 's3://${S3Bucket}/processed/'
        "--BEVERAGE_REGEX_PATTERNS": !Sub 's3://${S3Bucket}/mapping/regex/beverage_regex_patterns.yml'
        "--SIZE_REGEX_PATTERNS": !Sub 's3://${S3Bucket}/mapping/regex/size_regex_patterns.yml'
        "--CATEGORY_REGEX_PATTERN": !Sub 's3://${S3Bucket}/mapping/regex/category_regex_pattern.yml'
        "--ERROR_PATH": !Sub 's3://${S3Bucket}/error/transform/'

  QualityJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${Prefix}-quality-${Environment}"
      Role: !Ref GlueJobRoleArn
      GlueVersion: 4.0
      NumberOfWorkers: 10
      WorkerType: G.1X
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Sub 's3://${S3Bucket}/scripts/go-quality-elt.py'
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": "true"
        "--TempDir": !Sub 's3://${S3Bucket}/temp/'
        "--TRANSFORM_PATH": !Sub 's3://${S3Bucket}/transform/'
        "--THRESHOLDS_DICT_PATH": !Sub 's3://gp-elt-657082399901-dev/mapping/dict_restaurant/restaurant_thresholds.yaml'
        "--FINAL_PATH": !Sub 's3://${S3Bucket}/final/'
        "--QA_PATH": !Sub 's3://${S3Bucket}/quality/final/'
        "--QA_QUANTITY_PATH": !Sub 's3://${S3Bucket}/quality/quantity/'
        "--QA_PRICE_PATH": !Sub 's3://${S3Bucket}/quality/price/'
        "--PROCESS_PATH": !Sub 's3://${S3Bucket}/processed/transform/'
        "--ERROR_PATH": !Sub 's3://${S3Bucket}/error/quality/'
       

  MetricsJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${Prefix}-metrics-${Environment}"
      Role: !Ref GlueJobRoleArn
      GlueVersion: 4.0
      NumberOfWorkers: 10
      WorkerType: G.1X
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Sub 's3://${S3Bucket}/scripts/go-metric-elt.py'
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": "true"
        "--TempDir": !Sub 's3://${S3Bucket}/temp/'
        "--TRANSFORM_PATH": !Sub 's3://${S3Bucket}/transform/'
        "--FINAL_PATH": !Sub 's3://${S3Bucket}/final/'
        "--ERROR_PATH": !Sub 's3://${S3Bucket}/error/quality/'
        "--QUALITY_PATH": !Sub 's3://${S3Bucket}/quality/'
        "--METRICS_PATH": !Sub 's3://${S3Bucket}/metrics/'

Outputs:
  IngestJobName:
    Description: Name of the Glue ingestion job
    Value: !Ref IngestJob
    Export:
      Name: gp-glue-dev-IngestJobName

  TransformJobName:
    Description: Name of the Glue transformation job
    Value: !Ref TransformJob
    Export:
      Name: gp-glue-dev-TransformJobName

  QualityJobName:
    Description: Name of the Glue quality check job
    Value: !Ref QualityJob
    Export:
      Name: gp-glue-dev-QualityJobName

  MetricsJobName:
    Description: Name of the Glue metrics job
    Value: !Ref MetricsJob
    Export:
      Name: gp-glue-dev-MetricsJobName
