AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Workflow that chains Ingest, Transform, Quality, and Metrics Jobs

Parameters:
  Prefix:
    Type: String
  Environment:
    Type: String

Resources:
  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub "${Prefix}-glue-workflow-${Environment}"
      Description: Full ELT Workflow

  IngestTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${Prefix}-ingest-trigger-${Environment}"
      Type: ON_DEMAND
      WorkflowName: !Ref GlueWorkflow
      Actions:
        - JobName: !ImportValue "${Prefix}-glue-${Environment}-IngestJobName"

  TransformTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${Prefix}-transform-trigger-${Environment}"
      Type: CONDITIONAL
      WorkflowName: !Ref GlueWorkflow
      Predicate:
        Conditions:
          - JobName: !ImportValue "${Prefix}-glue-${Environment}-IngestJobName"
            LogicalOperator: EQUALS
            State: SUCCEEDED
      Actions:
        - JobName: !ImportValue "${Prefix}-glue-${Environment}-TransformJobName"

  QualityTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${Prefix}-quality-trigger-${Environment}"
      Type: CONDITIONAL
      WorkflowName: !Ref GlueWorkflow
      Predicate:
        Conditions:
          - JobName: !ImportValue "${Prefix}-glue-${Environment}-TransformJobName"
            LogicalOperator: EQUALS
            State: SUCCEEDED
      Actions:
        - JobName: !ImportValue "${Prefix}-glue-${Environment}-QualityJobName"

  MetricsTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${Prefix}-metrics-trigger-${Environment}"
      Type: CONDITIONAL
      WorkflowName: !Ref GlueWorkflow
      Predicate:
        Conditions:
          - JobName: !ImportValue "${Prefix}-glue-${Environment}-QualityJobName"
            LogicalOperator: EQUALS
            State: SUCCEEDED
      Actions:
        - JobName: !ImportValue "${Prefix}-glue-${Environment}-MetricsJobName"
